# Generated by Django 4.1.13 on 2024-10-06 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationP', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='email',
        ),
    ]
